name: ci
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - run: npm install
      - run: npm run test
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome e2e/**/*.fixture.ts --hostname localhost"
